/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iikh;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.print.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
/**
 *
 * @author abhinav
 */
public class MealManager extends javax.swing.JFrame {

    /**
     * Creates new form MealManager
     */
    PlanData pd;
    MealData m;
    public MealManager() {
        initComponents();
        setSize(820, 550);
        pd = new PlanData();
        
        ArrayList<String> arr = pd.planNames();
        ListRecipe1.removeAllItems();
        for(String x: arr)
        ListRecipe1.addItem(x);
        
        m = new MealData();
        ArrayList<String> rr = m.mealNames();
        b1.removeAllItems();l1.removeAllItems();d1.removeAllItems();
        b2.removeAllItems();l2.removeAllItems();d2.removeAllItems();
        b3.removeAllItems();l3.removeAllItems();d3.removeAllItems();
        b4.removeAllItems();l4.removeAllItems();d4.removeAllItems();
        b5.removeAllItems();l5.removeAllItems();d5.removeAllItems();
        b6.removeAllItems();l6.removeAllItems();d6.removeAllItems();
        b7.removeAllItems();l7.removeAllItems();d7.removeAllItems();
        for(String x: rr){
            b1.addItem(x);l1.addItem(x);d1.addItem(x);
            b2.addItem(x);l2.addItem(x);d2.addItem(x);
            b3.addItem(x);l3.addItem(x);d3.addItem(x);
            b4.addItem(x);l4.addItem(x);d4.addItem(x);
            b5.addItem(x);l5.addItem(x);d5.addItem(x);
            b6.addItem(x);l6.addItem(x);d6.addItem(x);
            b7.addItem(x);l7.addItem(x);d7.addItem(x);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        EditMeal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        ListRecipe = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        back1 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        DelMeal = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        name = new javax.swing.JTextField();
        AddMeal = new javax.swing.JButton();
        ViewRecipe = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EditPlan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ListRecipe1 = new javax.swing.JComboBox();
        back = new javax.swing.JButton();
        l4 = new javax.swing.JComboBox();
        DelPlan = new javax.swing.JButton();
        l1 = new javax.swing.JComboBox();
        l2 = new javax.swing.JComboBox();
        l3 = new javax.swing.JComboBox();
        name1 = new javax.swing.JTextField();
        CreatePlan = new javax.swing.JButton();
        ViewPlan = new javax.swing.JButton();
        b2 = new javax.swing.JComboBox();
        b1 = new javax.swing.JComboBox();
        b3 = new javax.swing.JComboBox();
        b4 = new javax.swing.JComboBox();
        d2 = new javax.swing.JComboBox();
        d1 = new javax.swing.JComboBox();
        d3 = new javax.swing.JComboBox();
        d4 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        b7 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        b6 = new javax.swing.JComboBox();
        b5 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        d5 = new javax.swing.JComboBox();
        d6 = new javax.swing.JComboBox();
        d7 = new javax.swing.JComboBox();
        l5 = new javax.swing.JComboBox();
        l6 = new javax.swing.JComboBox();
        l7 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel7.setText("Recipe3");

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel8.setText("Recipe4");

        EditMeal.setText("Edit Meal");
        EditMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMealActionPerformed(evt);
            }
        });

        jLabel5.setText("Recipe 1");

        jLabel2.setText("Name:");

        jLabel6.setText("Recipe2");

        jTextField3.setText("jTextField3");

        jTextField1.setText("jTextField1");

        ListRecipe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListRecipeActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        back1.setText("Back");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Set");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        DelMeal.setText("Delete Meal");
        DelMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelMealActionPerformed(evt);
            }
        });

        jButton4.setText("Set");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AddMeal.setText("Create Meal");
        AddMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMealActionPerformed(evt);
            }
        });

        ViewRecipe.setText("View Meal");
        ViewRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecipeActionPerformed(evt);
            }
        });

        jTextField4.setText("jTextField4");

        jButton2.setText("Set");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Set");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Plans");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 20, 123, 45);

        jLabel9.setText("Wednesday");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(6, 260, 80, 17);

        jLabel10.setText("Thursday");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(6, 304, 80, 17);

        EditPlan.setBackground(new java.awt.Color(255, 255, 255));
        EditPlan.setText("Save the edits");
        EditPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPlanActionPerformed(evt);
            }
        });
        getContentPane().add(EditPlan);
        EditPlan.setBounds(230, 480, 150, 29);

        jLabel11.setText("Monday");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(6, 175, 70, 17);

        jLabel3.setText("Plan Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 60, 90, 17);

        jLabel12.setText("Tuesday");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(6, 221, 80, 17);

        ListRecipe1.setBackground(new java.awt.Color(255, 255, 255));
        ListRecipe1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListRecipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListRecipe1ActionPerformed(evt);
            }
        });
        getContentPane().add(ListRecipe1);
        ListRecipe1.setBounds(502, 64, 160, 27);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(490, 480, 100, 29);

        l4.setBackground(new java.awt.Color(255, 255, 255));
        l4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(l4);
        l4.setBounds(321, 299, 140, 27);

        DelPlan.setBackground(new java.awt.Color(255, 255, 255));
        DelPlan.setText("Delete");
        DelPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelPlanActionPerformed(evt);
            }
        });
        getContentPane().add(DelPlan);
        DelPlan.setBounds(390, 480, 90, 29);

        l1.setBackground(new java.awt.Color(255, 255, 255));
        l1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(l1);
        l1.setBounds(321, 170, 140, 27);

        l2.setBackground(new java.awt.Color(255, 255, 255));
        l2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(l2);
        l2.setBounds(321, 208, 140, 27);

        l3.setBackground(new java.awt.Color(255, 255, 255));
        l3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(l3);
        l3.setBounds(321, 255, 140, 27);

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        getContentPane().add(name1);
        name1.setBounds(100, 90, 262, 27);

        CreatePlan.setBackground(new java.awt.Color(255, 255, 255));
        CreatePlan.setText("Add this Plan");
        CreatePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePlanActionPerformed(evt);
            }
        });
        getContentPane().add(CreatePlan);
        CreatePlan.setBounds(50, 480, 170, 29);

        ViewPlan.setBackground(new java.awt.Color(255, 255, 255));
        ViewPlan.setText("Browse");
        ViewPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPlanActionPerformed(evt);
            }
        });
        getContentPane().add(ViewPlan);
        ViewPlan.setBounds(668, 63, 100, 29);

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(b2);
        b2.setBounds(95, 208, 150, 27);

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(b1);
        b1.setBounds(95, 170, 150, 27);

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(b3);
        b3.setBounds(95, 257, 150, 27);

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(b4);
        b4.setBounds(95, 301, 150, 27);

        d2.setBackground(new java.awt.Color(255, 255, 255));
        d2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(d2);
        d2.setBounds(553, 208, 220, 27);

        d1.setBackground(new java.awt.Color(255, 255, 255));
        d1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(d1);
        d1.setBounds(553, 170, 220, 27);

        d3.setBackground(new java.awt.Color(255, 255, 255));
        d3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(d3);
        d3.setBounds(553, 257, 220, 27);

        d4.setBackground(new java.awt.Color(255, 255, 255));
        d4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(d4);
        d4.setBounds(553, 301, 220, 27);

        jLabel13.setText("Saturday");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(6, 393, 80, 17);

        b7.setBackground(new java.awt.Color(255, 255, 255));
        b7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(b7);
        b7.setBounds(95, 432, 150, 27);

        jLabel14.setText("Sunday");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(6, 437, 90, 17);

        b6.setBackground(new java.awt.Color(255, 255, 255));
        b6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(b6);
        b6.setBounds(95, 388, 150, 27);

        b5.setBackground(new java.awt.Color(255, 255, 255));
        b5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(b5);
        b5.setBounds(95, 339, 150, 27);

        jLabel15.setText("Friday");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(6, 344, 90, 17);

        d5.setBackground(new java.awt.Color(255, 255, 255));
        d5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(d5);
        d5.setBounds(553, 339, 220, 27);

        d6.setBackground(new java.awt.Color(255, 255, 255));
        d6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(d6);
        d6.setBounds(553, 388, 220, 27);

        d7.setBackground(new java.awt.Color(255, 255, 255));
        d7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(d7);
        d7.setBounds(553, 432, 220, 27);

        l5.setBackground(new java.awt.Color(255, 255, 255));
        l5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(l5);
        l5.setBounds(321, 339, 140, 27);

        l6.setBackground(new java.awt.Color(255, 255, 255));
        l6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(l6);
        l6.setBounds(321, 388, 140, 27);

        l7.setBackground(new java.awt.Color(255, 255, 255));
        l7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(l7);
        l7.setBounds(321, 432, 140, 27);

        jLabel4.setText("Dinner");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(553, 148, 80, 17);

        jLabel16.setText("Lunch");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(321, 148, 90, 17);

        jLabel17.setText("Breakfast");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(100, 150, 100, 17);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iikh/week.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, -10, 830, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        name.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void EditMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMealActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EditMealActionPerformed

    private void ListRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListRecipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListRecipeActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        Greeter gt= new Greeter();
        gt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField3.setText(jComboBox3.getSelectedItem().toString());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DelMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelMealActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DelMealActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField4.setText(jComboBox4.getSelectedItem().toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AddMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMealActionPerformed

    private void ViewRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecipeActionPerformed
        // TODO add your handling code here

    }//GEN-LAST:event_ViewRecipeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jComboBox2.getSelectedItem().toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EditPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPlanActionPerformed
        // TODO add your handling code here:
        ArrayList<String> rList = new ArrayList<>(Arrays.asList(
                b1.getSelectedItem().toString(), l1.getSelectedItem().toString(), d1.getSelectedItem().toString(),
                b2.getSelectedItem().toString(), l2.getSelectedItem().toString(), d2.getSelectedItem().toString(),
                b3.getSelectedItem().toString(), l3.getSelectedItem().toString(), d3.getSelectedItem().toString(),
                b4.getSelectedItem().toString(), l4.getSelectedItem().toString(), d4.getSelectedItem().toString(),
                b5.getSelectedItem().toString(), l5.getSelectedItem().toString(), d5.getSelectedItem().toString(),
                b6.getSelectedItem().toString(), l6.getSelectedItem().toString(), d6.getSelectedItem().toString(),
                b7.getSelectedItem().toString(), l7.getSelectedItem().toString(), d7.getSelectedItem().toString()
                )) ;
        
        if(name1.getText().equals("")){
            JOptionPane.showMessageDialog (jOptionPane1, "Enter valid name");
        }
        else{
            pd.editPlan(ListRecipe1.getSelectedItem().toString(), name1.getText(), rList);

            ArrayList<String> arr = pd.planNames();
            ListRecipe1.removeAllItems();
            for(String x: arr)
            ListRecipe1.addItem(x);
        }
    }//GEN-LAST:event_EditPlanActionPerformed

    private void ListRecipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListRecipe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListRecipe1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Greeter gt= new Greeter();
        gt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void DelPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelPlanActionPerformed
        // TODO add your handling code here:
        pd.removePlan(ListRecipe1.getSelectedItem().toString());

        ArrayList<String> arr = pd.planNames();
        ListRecipe1.removeAllItems();
        for(String x: arr)
        ListRecipe1.addItem(x);

        name1.setText("");
        b1.setSelectedItem("None");l1.setSelectedItem("None");d1.setSelectedItem("None");
        b2.setSelectedItem("None");l2.setSelectedItem("None");d2.setSelectedItem("None");
        b3.setSelectedItem("None");l3.setSelectedItem("None");d3.setSelectedItem("None");
        b4.setSelectedItem("None");l4.setSelectedItem("None");d4.setSelectedItem("None");
        b5.setSelectedItem("None");l5.setSelectedItem("None");d5.setSelectedItem("None");
        b6.setSelectedItem("None");l6.setSelectedItem("None");d6.setSelectedItem("None");
        b7.setSelectedItem("None");l7.setSelectedItem("None");d7.setSelectedItem("None");
    }//GEN-LAST:event_DelPlanActionPerformed

    private void CreatePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePlanActionPerformed
        // TODO add your handling code here:

        ArrayList<String> rList = new ArrayList<>(Arrays.asList(
                b1.getSelectedItem().toString(), l1.getSelectedItem().toString(), d1.getSelectedItem().toString(),
                b2.getSelectedItem().toString(), l2.getSelectedItem().toString(), d2.getSelectedItem().toString(),
                b3.getSelectedItem().toString(), l3.getSelectedItem().toString(), d3.getSelectedItem().toString(),
                b4.getSelectedItem().toString(), l4.getSelectedItem().toString(), d4.getSelectedItem().toString(),
                b5.getSelectedItem().toString(), l5.getSelectedItem().toString(), d5.getSelectedItem().toString(),
                b6.getSelectedItem().toString(), l6.getSelectedItem().toString(), d6.getSelectedItem().toString(),
                b7.getSelectedItem().toString(), l7.getSelectedItem().toString(), d7.getSelectedItem().toString()
                )) ;
        
        if(name1.getText().equals("")){
            JOptionPane.showMessageDialog (jOptionPane1, "Enter valid name");
        }
        else{
            JOptionPane.showMessageDialog(jOptionPane1, "Plan has been added");
            pd.addPlan(name1.getText(), rList);
            ArrayList<String> arr = pd.planNames();
            ListRecipe1.removeAllItems();
            for(String x: arr)
            ListRecipe1.addItem(x);
        }
    }//GEN-LAST:event_CreatePlanActionPerformed

    private void ViewPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPlanActionPerformed
        // TODO add your handling code here

        String rep = ListRecipe1.getSelectedItem().toString();
        if(rep == null){
            JOptionPane.showMessageDialog(jOptionPane1, "No plan found.");
            return ;
        }
        pd.getPlan(rep);
        name1.setText(rep);
        ArrayList<String> mls = pd.plans;
        
        b1.setSelectedItem(mls.get(0));l1.setSelectedItem(mls.get(1));d1.setSelectedItem(mls.get(2));
        b2.setSelectedItem(mls.get(3));l2.setSelectedItem(mls.get(4));d2.setSelectedItem(mls.get(5));
        b3.setSelectedItem(mls.get(6));l3.setSelectedItem(mls.get(7));d3.setSelectedItem(mls.get(8));
        b4.setSelectedItem(mls.get(9));l4.setSelectedItem(mls.get(10));d4.setSelectedItem(mls.get(11));
        b5.setSelectedItem(mls.get(12));l5.setSelectedItem(mls.get(13));d5.setSelectedItem(mls.get(14));
        b6.setSelectedItem(mls.get(15));l6.setSelectedItem(mls.get(16));d6.setSelectedItem(mls.get(17));
        b7.setSelectedItem(mls.get(18));l7.setSelectedItem(mls.get(19));d7.setSelectedItem(mls.get(20));
    }//GEN-LAST:event_ViewPlanActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MealManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MealManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MealManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MealManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MealManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMeal;
    private javax.swing.JButton CreatePlan;
    private javax.swing.JButton DelMeal;
    private javax.swing.JButton DelPlan;
    private javax.swing.JButton EditMeal;
    private javax.swing.JButton EditPlan;
    private javax.swing.JComboBox ListRecipe;
    private javax.swing.JComboBox ListRecipe1;
    private javax.swing.JButton ViewPlan;
    private javax.swing.JButton ViewRecipe;
    private javax.swing.JComboBox b1;
    private javax.swing.JComboBox b2;
    private javax.swing.JComboBox b3;
    private javax.swing.JComboBox b4;
    private javax.swing.JComboBox b5;
    private javax.swing.JComboBox b6;
    private javax.swing.JComboBox b7;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox d1;
    private javax.swing.JComboBox d2;
    private javax.swing.JComboBox d3;
    private javax.swing.JComboBox d4;
    private javax.swing.JComboBox d5;
    private javax.swing.JComboBox d6;
    private javax.swing.JComboBox d7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox l1;
    private javax.swing.JComboBox l2;
    private javax.swing.JComboBox l3;
    private javax.swing.JComboBox l4;
    private javax.swing.JComboBox l5;
    private javax.swing.JComboBox l6;
    private javax.swing.JComboBox l7;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    // End of variables declaration//GEN-END:variables
}
