/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iikh;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author abhinav
 */
public class PlanManager extends javax.swing.JFrame {

    /**
     * Creates new form PlanManager
     */
    MealData md;
    Database d;
    public PlanManager() {
        
        initComponents();
        setSize(790, 470);
        md = new MealData();
        
        ArrayList<String> arr = md.mealNames();
        ListRecipe.removeAllItems();
        for(String x: arr)
        ListRecipe.addItem(x);
        
        d = new Database();
        ArrayList<String> rr = d.repNames();
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        jComboBox4.removeAllItems();
        for(String x: rr){
            jComboBox1.addItem(x);
            jComboBox2.addItem(x);
            jComboBox3.addItem(x);
            jComboBox4.addItem(x);
        }
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jMenu1 = new javax.swing.JMenu();
        ListRecipe = new javax.swing.JComboBox();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        EditMeal = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        AddMeal = new javax.swing.JButton();
        ViewRecipe = new javax.swing.JButton();
        DelMeal = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ListRecipe.setBackground(new java.awt.Color(255, 255, 255));
        ListRecipe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListRecipeActionPerformed(evt);
            }
        });
        getContentPane().add(ListRecipe);
        ListRecipe.setBounds(490, 40, 110, 26);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(530, 370, 97, 30);

        jLabel2.setText("Meal Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 40, 80, 16);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Meals Manager");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(313, 0, 190, 32);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(440, 370, 80, 28);

        EditMeal.setBackground(new java.awt.Color(255, 255, 255));
        EditMeal.setText("Save edits");
        EditMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMealActionPerformed(evt);
            }
        });
        getContentPane().add(EditMeal);
        EditMeal.setBounds(200, 370, 100, 28);
        getContentPane().add(name);
        name.setBounds(40, 60, 262, 28);

        AddMeal.setBackground(new java.awt.Color(255, 255, 255));
        AddMeal.setText("Add this Meal");
        AddMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMealActionPerformed(evt);
            }
        });
        getContentPane().add(AddMeal);
        AddMeal.setBounds(60, 370, 130, 28);

        ViewRecipe.setBackground(new java.awt.Color(255, 255, 255));
        ViewRecipe.setText("Browse");
        ViewRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecipeActionPerformed(evt);
            }
        });
        getContentPane().add(ViewRecipe);
        ViewRecipe.setBounds(630, 40, 110, 28);

        DelMeal.setBackground(new java.awt.Color(255, 255, 255));
        DelMeal.setText("Delete");
        DelMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelMealActionPerformed(evt);
            }
        });
        getContentPane().add(DelMeal);
        DelMeal.setBounds(310, 370, 120, 28);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(40, 100, 230, 26);

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(40, 150, 230, 26);

        jComboBox3.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(40, 190, 230, 26);

        jComboBox4.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(40, 230, 229, 26);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(310, 100, 210, 28);

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(310, 140, 210, 28);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(310, 180, 210, 28);

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(310, 230, 210, 28);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add this recipe to meal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 100, 180, 28);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add this recipe to meal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(560, 140, 180, 28);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add this recipe to meal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 180, 180, 28);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add this recipe to meal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(560, 230, 180, 28);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iikh/meal.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListRecipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListRecipeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Greeter gt= new Greeter();
        gt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        name.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void EditMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMealActionPerformed
        // TODO add your handling code here:
        ArrayList<String> rList = new ArrayList<>(Arrays.asList(jTextField1.getText())) ;
        if(!jTextField2.getText().equals(""))rList.add(jTextField2.getText());
        if(!jTextField3.getText().equals(""))rList.add(jTextField3.getText());
        if(!jTextField4.getText().equals(""))rList.add(jTextField4.getText());
        
         if(rList.get(0).equals("") || rList.get(1).equals("")){
            JOptionPane.showMessageDialog (jOptionPane1, "Enter valid values");
        }
        else{
            md.editMeal(ListRecipe.getSelectedItem().toString(), name.getText(), rList);
            ArrayList<String> arr = md.mealNames();
            ListRecipe.removeAllItems();
            for(String x: arr)
            ListRecipe.addItem(x);
         }
    }//GEN-LAST:event_EditMealActionPerformed

    private void AddMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMealActionPerformed
        // TODO add your handling code here:

        ArrayList<String> rList = new ArrayList<>(Arrays.asList(jTextField1.getText())) ;
        if(!jTextField2.getText().equals(""))rList.add(jTextField2.getText());
        if(!jTextField3.getText().equals(""))rList.add(jTextField3.getText());
        if(!jTextField4.getText().equals(""))rList.add(jTextField4.getText());
        
        if(rList.get(0).equals("") || rList.get(1).equals("")){
            JOptionPane.showMessageDialog (jOptionPane1, "Enter valid values");
        }
        else{
            JOptionPane.showMessageDialog(jOptionPane1, "Meal has been added");
            md.addMeal(name.getText(), rList);
            ArrayList<String> arr =md.mealNames();
            ListRecipe.removeAllItems();
            for(String x: arr)
            ListRecipe.addItem(x);
        }
    }//GEN-LAST:event_AddMealActionPerformed

    private void ViewRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecipeActionPerformed
        // TODO add your handling code here

        String rep = ListRecipe.getSelectedItem().toString();
        if(rep == null){
            JOptionPane.showMessageDialog(jOptionPane1, "No meal found.");
            return ;
        }
        md.getMeal(rep);
        name.setText(rep);
        ArrayList<String> mls = md.meals;
        switch(mls.size()){
            case 4:jTextField4.setText(mls.get(3));
            case 3:jTextField3.setText(mls.get(2));
            case 2:jTextField2.setText(mls.get(1));
            case 1:jTextField1.setText(mls.get(0));
                break;
        }
        
        if(mls.size()==3){
            jTextField4.setText("");
        }
        else if(mls.size()==2){
            jTextField4.setText("");
            jTextField3.setText("");
        }
        else if(mls.size()==1){
            jTextField4.setText("");
            jTextField3.setText("");
            jTextField2.setText("");
        }
    }//GEN-LAST:event_ViewRecipeActionPerformed

    private void DelMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelMealActionPerformed
        // TODO add your handling code here:
        md.removeMeal(ListRecipe.getSelectedItem().toString());

        ArrayList<String> arr = md.mealNames();
        ListRecipe.removeAllItems();
        for(String x: arr)
        ListRecipe.addItem(x);

        name.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_DelMealActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jComboBox2.getSelectedItem().toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField3.setText(jComboBox3.getSelectedItem().toString());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField4.setText(jComboBox4.getSelectedItem().toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMeal;
    private javax.swing.JButton DelMeal;
    private javax.swing.JButton EditMeal;
    private javax.swing.JComboBox ListRecipe;
    private javax.swing.JButton ViewRecipe;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
