/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iikh;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author abhinav
 */
public class RecipeForm extends javax.swing.JFrame {

    /**
     * Creates new form RecipeForm
     */
    Database db;
    public RecipeForm() {
        initComponents();
        db = new Database();
        
        ArrayList<String> arr = db.repNames();
        ListRecipe.removeAllItems();
        for(String x: arr)
        ListRecipe.addItem(x);
        setSize(670, 480);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        ListRecipe = new javax.swing.JComboBox();
        AddRecipe = new javax.swing.JButton();
        DelRecipe = new javax.swing.JButton();
        ViewRecipe = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingr = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        inst = new javax.swing.JTextArea();
        EditRecipe = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recipe Manager");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 0, 210, 32);

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 30, 37, 16);

        jLabel3.setText("Ingredients:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(29, 97, 100, 16);

        jLabel4.setText("How to Prepare:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(29, 247, 120, 16);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(460, 290, 141, 30);

        ListRecipe.setBackground(new java.awt.Color(255, 255, 255));
        ListRecipe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListRecipeActionPerformed(evt);
            }
        });
        getContentPane().add(ListRecipe);
        ListRecipe.setBounds(433, 45, 100, 26);

        AddRecipe.setBackground(new java.awt.Color(255, 255, 255));
        AddRecipe.setText("Add this Recipe");
        AddRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRecipeActionPerformed(evt);
            }
        });
        getContentPane().add(AddRecipe);
        AddRecipe.setBounds(460, 130, 140, 28);

        DelRecipe.setBackground(new java.awt.Color(255, 255, 255));
        DelRecipe.setText("Delete this Recipe");
        DelRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelRecipeActionPerformed(evt);
            }
        });
        getContentPane().add(DelRecipe);
        DelRecipe.setBounds(460, 210, 140, 28);

        ViewRecipe.setBackground(new java.awt.Color(255, 255, 255));
        ViewRecipe.setText("Browse");
        ViewRecipe.setBorder(null);
        ViewRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecipeActionPerformed(evt);
            }
        });
        getContentPane().add(ViewRecipe);
        ViewRecipe.setBounds(539, 44, 70, 30);

        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(30, 60, 296, 30);

        ingr.setColumns(20);
        ingr.setRows(5);
        jScrollPane1.setViewportView(ingr);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(29, 125, 353, 110);

        inst.setColumns(20);
        inst.setRows(5);
        jScrollPane2.setViewportView(inst);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(29, 269, 353, 111);

        EditRecipe.setBackground(new java.awt.Color(255, 255, 255));
        EditRecipe.setText("Save the changes");
        EditRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditRecipeActionPerformed(evt);
            }
        });
        getContentPane().add(EditRecipe);
        EditRecipe.setBounds(460, 170, 140, 28);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear text");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(460, 250, 140, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iikh/recipes.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 640, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListRecipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListRecipeActionPerformed

    private void AddRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRecipeActionPerformed
        // TODO add your handling code here:
        
        String ingrs[] = ingr.getText().split("\\r?\\n");
        ArrayList<String>arrList = new ArrayList<>(Arrays.asList(ingrs)) ;
        String insts[] = inst.getText().split("\\r?\\n");
        ArrayList<String>arrList2 = new ArrayList<>(Arrays.asList(insts)) ;
        if(ingrs[0].equals("") || insts[0].equals("")){
            JOptionPane.showMessageDialog (jOptionPane1, "Enter valid values");
        }
        else{
            JOptionPane.showMessageDialog(jOptionPane1, "Recipe has been added");
            db.addRecipe(name.getText(), arrList, arrList2);

            name.setText("");
            ingr.setText("");
            inst.setText("");
            
            ArrayList<String> arr = db.repNames();
            ListRecipe.removeAllItems();
            for(String x: arr)
            ListRecipe.addItem(x);
        }
    }//GEN-LAST:event_AddRecipeActionPerformed

    private void ViewRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecipeActionPerformed
        // TODO add your handling code here
        
        String rep = ListRecipe.getSelectedItem().toString();
        db.getRecipe(rep);
        ingr.setText("");
        inst.setText("");
        name.setText(rep);
        ArrayList<String> itm = db.indegrients;
        ArrayList<String> mtd = db.method;
        for(String x : itm)
            ingr.append(x + "\n");
        for(String x: mtd)
            inst.append(x + "\n");
        
    }//GEN-LAST:event_ViewRecipeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Greeter gt= new Greeter();
        gt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void DelRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelRecipeActionPerformed
        // TODO add your handling code here:
        db.removeRecipe(ListRecipe.getSelectedItem().toString());
        
        ArrayList<String> arr = db.repNames();
        ListRecipe.removeAllItems();
        for(String x: arr)
        ListRecipe.addItem(x);
        
        name.setText("");
        ingr.setText("");
        inst.setText("");
    }//GEN-LAST:event_DelRecipeActionPerformed

    private void EditRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditRecipeActionPerformed
        // TODO add your handling code here:
        String ingrs[] = ingr.getText().split("\\r?\\n");
        ArrayList<String>arrList = new ArrayList<>(Arrays.asList(ingrs)) ;
        String insts[] = inst.getText().split("\\r?\\n");
        ArrayList<String>arrList2 = new ArrayList<>(Arrays.asList(insts)) ;
        
        if(ingrs[0].equals("") || insts[0].equals("")){
            JOptionPane.showMessageDialog (jOptionPane1, "Enter valid values");
        }
        else{
            JOptionPane.showMessageDialog(jOptionPane1, "Changes made in this recipe are saved");
            db.editRecipe(ListRecipe.getSelectedItem().toString(), name.getText(), arrList, arrList2);
        
            ArrayList<String> arr = db.repNames();
            ListRecipe.removeAllItems();
            for(String x: arr)
            ListRecipe.addItem(x);
        }
    }//GEN-LAST:event_EditRecipeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        name.setText("");
        ingr.setText("");
        inst.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if(name.getText().isEmpty()) {
                    name.setText("Enter the recipe name here");
                }
    }//GEN-LAST:event_nameFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if(name.getText().equals("Enter the recipe name here")) {
                    name.setText("");
                }
    }//GEN-LAST:event_nameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRecipe;
    private javax.swing.JButton DelRecipe;
    private javax.swing.JButton EditRecipe;
    private javax.swing.JComboBox ListRecipe;
    private javax.swing.JButton ViewRecipe;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JTextArea ingr;
    private javax.swing.JTextArea inst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
